### PR TITLE
Run cargo update to update dependencies.

### PR DESCRIPTION
**Pull request by hramrach**

### CODE REVIEW

**Comment by patjak** [comment]
Hi Michal, I just sent a pull request trying to fix issue #13. I assume this is intended to do the same. I know absolutely nothing about rust but I think the lock file isn't supposed to be edited but instead update the .toml file and let .lock be generated.

**Comment by hramrach** [comment]
I did not edit the file. It was updated by cargo update.

**Comment by patjak** [comment]
Right, but should you also update the toml file?

**Comment by hramrach** [comment]
https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html

**Comment by patjak** [comment]
Ok, and since the version dependency specified in .toml allows rayon to be upgraded everything is fine.
Thanks, that's all I needed to know.

**Comment by hramrach** [comment]
As far as I understand it the toml file describes the interface used and the lock file the implementation used. The lock file should be updated, and the toml file may be updated together with the lock file. Updating toml file alone should trigger lock file update on next build which in turn should be checked in to prevent conflicts in trees used to build the program.

**Pull request merged**
